const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN'
const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'

const GET_USERS_BEGIN = 'GET_USERS_BEGIN'
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'

const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS '

const CLEAR_ALERT = 'CLEAR_ALERT'
const SHOW_ALERT = 'SHOW_ALERT'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

const ADD_TASK_BEGIN = 'ADD_TASK_BEGIN'
const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
const ADD_TASK_ERROR = 'ADD_TASK_ERROR'

const GET_TASKS_BEGIN = 'GET_TASKS_BEGIN'
const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
const GET_TASKS_ERROR = 'GET_TASKS_ERROR'

const GET_LISTS_BEGIN = 'GET_LISTS_BEGIN'
const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS'

const GET_SINGLE_LIST_BEGIN = 'GET_SINGLE_LIST_BEGIN'
const GET_SINGLE_LIST_SUCCESS = 'GET_SINGLE_LIST_SUCCESS'

const ADD_LIST_BEGIN = 'ADD_LIST_BEGIN'
const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS'
const ADD_LIST_ITEM_BEGIN = 'ADD_LIST_ITEM_BEGIN'
const ADD_LIST_ITEM_SUCCESS = 'ADD_LIST_ITEM_SUCCESS'

const SHOW_MODAL = 'SHOW_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'

const UPDATE_TASK_START = 'UPDATE_TASK_START'
const UPDATE_TASK_COMPLETED = 'UPDATE_TASK_COMPLETED'

const SEND_FRIEND_REQUEST_BEGIN = 'SEND_FRIEND_REQUEST_BEGIN'
const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS'

export {
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  GET_CURRENT_USER_BEGIN,
  GET_CURRENT_USER_SUCCESS,
  LOGOUT_SUCCESS,
  CLEAR_ALERT,
  SHOW_ALERT,
  TOGGLE_SIDEBAR,
  ADD_TASK_BEGIN,
  ADD_TASK_SUCCESS,
  ADD_TASK_ERROR,
  GET_LISTS_BEGIN,
  GET_LISTS_SUCCESS,
  GET_TASKS_ERROR,
  SHOW_MODAL,
  CLOSE_MODAL,
  ADD_LIST_BEGIN,
  ADD_LIST_SUCCESS,
  ADD_LIST_ITEM_BEGIN,
  ADD_LIST_ITEM_SUCCESS,
  GET_SINGLE_LIST_BEGIN,
  GET_SINGLE_LIST_SUCCESS,
  GET_TASKS_BEGIN,
  GET_TASKS_SUCCESS,
  UPDATE_TASK_START,
  UPDATE_TASK_COMPLETED,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  GET_USERS_BEGIN,
  GET_USERS_SUCCESS,
  SEND_FRIEND_REQUEST_BEGIN,
  SEND_FRIEND_REQUEST_SUCCESS,
}
