const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN'
const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'

const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS '

const CLEAR_ALERT = 'CLEAR_ALERT'
const SHOW_ALERT = 'SHOW_ALERT'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

const ADD_TASK_BEGIN = 'ADD_TASK_BEGIN'
const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
const ADD_TASK_ERROR = 'ADD_TASK_ERROR'

export {
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  GET_CURRENT_USER_BEGIN,
  GET_CURRENT_USER_SUCCESS,
  LOGOUT_SUCCESS,
  CLEAR_ALERT,
  SHOW_ALERT,
  TOGGLE_SIDEBAR,
  ADD_TASK_BEGIN,
  ADD_TASK_SUCCESS,
  ADD_TASK_ERROR,
}
